---
- name: User Playbook
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks: 
  - name: User add bob
    user:
     name: bob
     comment: "John Smith"
     groups: wheel
     generate_ssh_keys: yes
     state: present

  - name: User add lisa 
    user:
     name: lisa
     state: absent
